import type { Metadata } from "next";

import { ClientComponent, StoreProvider, SetCartProvider } from "../components";

import { SetCartContext } from "../utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SetCartProvider>
          <StoreProvider>
            <ClientComponent />
            {children}
          </StoreProvider>
        </SetCartProvider>
      </body>
    </html>
  );
}
